### ISSUE TITLE
Replace UiKit css with Bootstrap

### ISSUE THREAD

**Issue by rafalopilowski1** [pjatk21/pjatk-cat-guard#15]
- [x] Make admin webpanel mobile-friendly
- [x] Examine UX desicions
- [x] Switch from `<table>` to flex items

UX work will be done on Figma team

**Comment by kpostekk** [comment]
Merged into main

**Comment by rafalopilowski1** [comment]
Closing as transition was made
